apiVersion: skaffold/v3
kind: Config
metadata:
  name: canary
requires:
- path: ./deployment/applications/identities
  activeProfiles:
  - name: staging
    activatedBy:
    - staging
profiles:
- name: staging
