apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: canary
requires:
- path: ./deployment/applications/identities
  activeProfiles:
  - name: prod
    activatedBy:
    - prod
profiles:
- name: prod
