apiVersion: skaffold/v3
kind: Config
metadata:
  name: service-starter
build:
  artifacts:
    - image: renegadelabs.io/canary-service-starter
      custom:
        buildCommand:
          USE_BUILDPACK=paketobuildpacks/builder:base
          USE_NATIVE_COMPILER=false
          ../../../gradlew bootBuildImage
          -p ../../../service-starter
          --stacktrace
          --console=verbose
        dependencies:
          paths:
            - ../../../service-starter/src/main/**
            - ../../../shared/src/main/**
deploy:
  helm:
    releases:
      - name: service-starter
        chartPath: ../../
        valuesFiles:
          - ./values-common.yaml
        namespace: canary
        createNamespace: true
profiles:
  - name: prod
    patches:
      - op: replace
        path: /build/artifacts/0/custom/buildCommand
        value:
          USE_BUILDPACK=paketobuildpacks/builder:tiny
          USE_NATIVE_COMPILER=true
          ../../../gradlew bootBuildImage
          -p ../../../service-starter
          --stacktrace
          --console=verbose
      - op: add
        path: /build/artifacts/0/tagPolicy
        value:
          customTemplate:
            components:
              - gitCommit:
                  variant: AbbrevCommitSha
                name: GIT_COMMIT
              - dateTime:
                  format: 2006-01-02_15-04-05
                  timezone: UTC
                name: DATE_TIME
            template: '{{.GIT_COMMIT}}_{{.DATE_TIME}}'
