apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: service-starter
build:
  artifacts:
  - image: renegadelabs.io/canary-service-starter
    custom:
      buildCommand:
        set USE_BUILDPACK=paketobuildpacks/builder:base&&
        set USE_NATIVE_COMPILER=false&&
        ..\..\..\gradlew -p ../../../service-starter bootBuildImage --stacktrace --console=verbose
      dependencies:
        paths:
        - ../../../service-starter/src/main/**
        - ../../../shared/src/main/**
deploy:
  helm:
    releases:
    - name: service-starter
      chartPath: ../../
      artifactOverrides:
        image: renegadelabs.io/canary-service-starter
      namespace: canary
      createNamespace: true
      valuesFiles:
      - ./values-common.yaml
      - ./values-dev.yaml
profiles:
- name: prod
  patches:
  - op: replace
    path: /build/artifacts/0/custom/buildCommand
    value:
      set USE_BUILDPACK=paketobuildpacks/builder:tiny&&
      set USE_NATIVE_COMPILER=true&&
      ..\..\..\gradlew -p ../../../service-starter bootBuildImage --stacktrace --console=verbose
  - op: add
    path: /build/artifacts/0/tagPolicy
    value:
      customTemplate:
        template: '{{.GIT_COMMIT}}_{{.DATE_TIME}}'
        components:
        - name: GIT_COMMIT
          gitCommit:
            variant: AbbrevCommitSha
        - name: DATE_TIME
          dateTime:
            format: 2006-01-02_15-04-05
            timezone: UTC
