image: renegadelabs.io/canary-service-starter
imagePullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: "service-starter"
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}

replicaCount: 1

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: api.canary.local
      paths:
        - path: /service-starter
          pathType: Prefix

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false