spring:
  cloud:
    environment:
      enabled: false
  flyway:
    baseline-on-migrate: true
    fail-on-missing-locations: true
    locations: classpath:db/migration/h2
    url: jdbc:h2:mem:///
  r2dbc:
    url: r2dbc:h2:mem:///
    username: dbuser
    password: changeit
    name: shared
    properties:
      DB_CLOSE_DELAY: -1
      DB_CLOSE_ON_EXIT: FALSE
      MODE: PostgreSQL
