spring:
  flyway:
    url: jdbc:h2:mem:///canary;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;USER=dbuser;PASSWORD=changeit;
    schemas: IDENTITIES
    table: FLYWAY_SCHEMA_HISTORY
    baseline-on-migrate: true
    fail-on-missing-locations: true
    locations: classpath:db/migration/h2
  r2dbc:
    url: r2dbc:h2:mem:///canary;MODE=PostgreSQL;USER=dbuser;PASSWORD=changeit;SCHEMA=IDENTITIES
