apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: service-starter
build:
  artifacts:
  - image: renegadelabs.io/canary-service-starter
    custom:
      buildCommand: set USE_BUILDPACK=paketobuildpacks/builder:base&& set USE_NATIVE_COMPILER=false&&
        ..\gradlew bootBuildImage --stacktrace --console=verbose
      dependencies:
        paths:
        - src/main/**
        - ../shared/src/main/**
deploy:
  helm:
    releases:
    - name: service-starter
      chartPath: .
      artifactOverrides:
        image: renegadelabs.io/canary-service-starter
      namespace: canary
      createNamespace: true
profiles:
- name: prod
  build:
    artifacts:
    - image: renegadelabs.io/canary-service-starter
      custom:
        buildCommand: set USE_BUILDPACK=paketobuildpacks/builder:tiny&& set USE_NATIVE_COMPILER=true&&
          ..\gradlew bootBuildImage --stacktrace --console=verbose
        dependencies:
          paths:
          - src/main/**
          - ../shared/src/main/**
    tagPolicy:
      customTemplate:
        template: '{{.GIT_COMMIT}}_{{.DATE_TIME}}'
        components:
        - name: GIT_COMMIT
          gitCommit:
            variant: AbbrevCommitSha
        - name: DATE_TIME
          dateTime:
            format: 2006-01-02_15-04-05
            timezone: UTC
