logging:
  level:
    org.flywaydb.core.internal.database.base.BaseDatabaseType: ERROR
    org.flywaydb.core.internal.license.VersionPrinter: ERROR
management:
  endpoint:
    health:
      probes:
        enabled: true
spring:
  application:
    name: identities
  cloud:
    environment:
      enabled: false
  profiles:
    default: development
    group:
      development: development, h2
      test: test, postgresql
      staging: staging, postgresql
  r2dbc:
    pool:
      enabled: true
      initial-size: 10
      max-size: 100
  sql:
    init:
      mode: never
  webflux:
    base-path: /${spring.application.name}
