CREATE TABLE IF NOT EXISTS identity (
    id                      bigint      not null generated by default as identity primary key,
    username                text        not null unique,
    password                text        not null,
    authorities             text array  not null,
    expired                 boolean     not null,
    locked                  boolean     not null,
    credentials_expired     boolean     not null,
    disabled                boolean     not null
);
